### ISSUE TITLE
Text decoration

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1675-assignment-1#2]
For some reason, my button for "See Show Times" has a text-decoration. I've selected the element to check it in chrome and I can't figure out why it isn't applying.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
I think it’s because there is a `<div>` inside the `<a>` tag. Try putting the `class` directly on the `<a>` tag then deleting the `<div>`… I think that'll work better.

The reason the text decoration isn't getting removed is because it’s the `<a>` tag that has the property, no the `<div>` inside it.
